### ISSUE TITLE
Xmake not building on Intel Mac

### ISSUE THREAD

**Issue by marnovandermaas** [lowRISC/lowrisc-nix#40]
![image](https://github.com/lowRISC/lowrisc-nix/assets/34654485/16106829-5410-4afc-969a-67e8f4a5053b)

This error goes away when I build without this patch: https://github.com/lowRISC/lowrisc-nix/blob/main/pkgs/xmake/macosx.patch

**Comment by marnovandermaas** [comment]
Also reported here: https://github.com/lowRISC/sonata-system/issues/96#issuecomment-2133096665

**Comment by hcallahan-lowrisc** [comment]
Closed by #41, please re-open if you see this error again.
