### ISSUE TITLE
buildFHSEnvOverlay doesn't currently work on kernels older than 5.3

### ISSUE THREAD

**Issue by hcallahan-lowrisc** [lowRISC/lowrisc-nix#62]
The `--kill-child` argument to unshare uses the `pidfd_open` syscall, which is not available on linux kernels older than 5.3
This is an issue when trying to run on enterprise linux with older kernels, such as RHEL / Rocky 8, which use 4.18

https://github.com/lowRISC/lowrisc-nix/blob/764a76080cff9a22a3fc31c0f35c01c1532d6eee/lib/buildFHSEnvOverlay.nix#L195

Removing `--kill-child` allows the environment to work, although from discussions in-person this has implications for cleaning up bazel processes, so is not a full solution.

**Comment by nbdd0121** [comment]
I think actually neither `--fork` and `--kill-child` are needed here. `--kill-child` can only reliability kill Bazel daemons if we use it with pid namespaces, but I didn't enable it for now.
